### ISSUE TITLE
Song Genre Name return undefined crashes app

### ISSUE THREAD

**Issue by syntaxhacker** [bradtraversy/lyricfinder#1]
hi  sir ,
following your tutorial and working with it i came across an issue with song genre in **Lyrics.js**  which is not available for some songs . So Api just return `track.primary_genres.music_genre_list` of length zero and when we click lyrics whole app crashes so your users will not be able to follow your tutorial. so i modified it as ` { track.primary_genres.music_genre_list.length === 0 ? 'NO GENRE AVAILABLE' : track.primary_genres.music_genre_list[0].music_genre.music_genre_name }` . do modify it in your repo sir thankyou you are awesome.

**Comment by bradtraversy** [comment]
Can you please make a pull request and add it? I will accept

**Comment by syntaxhacker** [comment]
Done
